# Generated by Django 3.0.4 on 2021-05-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturant",
            name="location",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
