# Generated by Django 3.0.4 on 2021-05-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturants", "0002_resturant_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturant",
            name="category",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
