# Generated by Django 3.0.4 on 2021-05-03 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("resturants", "0003_resturant_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturant",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
