# Generated by Django 3.0.4 on 2021-05-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturants", "0004_resturant_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturant",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
