# Generated by Django 3.0.4 on 2021-05-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturants", "0005_auto_20210503_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturant",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
