# Generated by Django 3.0.4 on 2021-05-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturants", "0006_auto_20210503_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturant",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="resturant",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
